### ISSUE TITLE
docs would be great

### ISSUE THREAD

**Issue by d-v-b** [JaneliaSciComp/pydantic-ome-ngff#12]
mkdocs?

**Comment by k-dominik** [comment]
in addition to developer docs, it would be great to have some real world example of how to, say go from a url to an ome-zarr to something useful, validated in here...

**Comment by d-v-b** [comment]
@k-dominik I totally agree! I just opened a PR that adds docs (https://github.com/JaneliaSciComp/pydantic-ome-ngff/pull/19)

>  say go from a url to an ome-zarr to something useful, validated in here...

When you say "something useful", what would that be, exactly? Like, a Zarr group, or a Zarr group + all the Zarr arrays referenced by one of the elements of `multiscales`?

**Comment by k-dominik** [comment]
Hi @d-v-b,

thank you so much for the super quick reply! I guess zarr groups and validated metadata (mainly interested in `Multiscales`) would be what I was looking for. :)

Cheers
Dominik

**Comment by d-v-b** [comment]
@k-dominik if you have time, take a look at the [example](https://github.com/JaneliaSciComp/pydantic-ome-ngff/blob/use_pydantic_zarr/docs/index.md#creating-multiscale-metadata) I added to the docs in #19 , is this useful?

**Comment by k-dominik** [comment]
Hello @d-v-b,

thank you for adding this example, it's great to see the library in action! Also the example you added for reading is super helpful.

One question: Is there a particular reason the metadata needs a reference to the arrays. I mean I get that `to_zarr` and `from_zarr` can use/return a single object only, but otherwise the metadata could be serialized/passed/reused around independently. I think I would prefer to have a metadata-only object, which would have enough information to access the zarr-arrays as needed. Is there already a layer to address this?

Cheers and thank you again!

Dominik

**Comment by d-v-b** [comment]
> One question: Is there a particular reason the metadata needs a reference to the arrays.

I don't think I understand this question, so let me know if this attempt to answer it is unhelpful:

An OME-NGFF multiscale group is basically a Zarr group + some metadata + some zarr arrays. The metadata references arrays; for that metadata to be validated, the validation logic must use some model of a zarr array, to ensure that the stuff in the metadata is making a valid reference, and that the coordinate transformations have the same number of dimensions as the corresponding array, that kind of thing. 

The `Group.from_arrays` method is a convenience method that creates a _model_ of a zarr array from each of the arrays provided to that method, validates those models against the `coordinateTransformations`, puts them in a model of a zarr group, etc. It doesn't keep a reference to the arrays, or do anything with their data. It just takes their shape and dtype, and makes an `ArraySpec` for each one, so that it can model the entire Zarr hierarchy. To make this more clear I guess `from_arrays` could be modified to take just the shapes and dtypes as arguments, but that's actually less convenient when you already have your arrays (which, presumably, describes anyone about to write an OME-NGFF zarr group).

>  I think I would prefer to have a metadata-only object, which would have enough information to access the zarr-arrays as needed. Is there already a layer to address this?

_Everything_ in this library is "metadata-only", except the `from_zarr` and `to_zarr` methods, which create metadata from stored stuff, or do that process in reverse, respectively, and those methods come from a dependency :)

For the lower-level metadata models (like the model of [`multiscales`](https://github.com/JaneliaSciComp/pydantic-ome-ngff/blob/7a28df76b8e24bd8537b04002a2ae4f3396447ac/src/pydantic_ome_ngff/v04/multiscale.py#L161) metadata), there's API documentation, but it's programmatically generated, I don't have a preview ready. But as I mentioned earlier, this metadata references arrays (`multiscale.datasets` is a list of descriptions of Zarr arrays), so it's not clear how useful this is if you don't want to reference arrays...

**Comment by k-dominik** [comment]
I get your point. For the validation though, I'd argue a shape would be enough. But having it so tight with the the reference to the array ensures even more, that the metadata is valid for a zarr.

I looked around and found `MultiscaleMetadata` to be more or less what I would be want to be working with and I think your example can be applied to that as well. :)

**Comment by d-v-b** [comment]
thanks for the feedback @virginiascarlett! I incorporated some of your suggestions. 

> I agree with @k-dominik that it seems reasonable that the user should be able to instantiate a Group using only shape and dtype, since that's the only information the package actually needs, but what do I know. ¯_(ツ)_/¯

Under the hood, the method under discussion calls [`ArraySpec.from_array`](https://janelia-cellmap.github.io/pydantic-zarr/api/v2/#pydantic_zarr.v2.ArraySpec.from_array), which takes an array-like object as its input and makes a Zarr array that has properties (like shape and dtype, but potentially other properties as well) derived from that input. For example, if you call `ArraySpec.from_array(my_zarr_array)`, the resulting `ArraySpec` object will keep the `chunks`, `compressor`, `attrs`, etc attributes of `my_zarr_array` (and you can override this behavior if you want). `Group.from_arrays` exposes the same functionality, which is convenient if people want to convert existing zarr arrays into and OME-NGFF group with minimal changes.

But if this turns out to be a bad decision, I'm happy to make alterations as needed :)

> What feels potentially missing to me is some examples of validation, like, as if you received some data from a collaborator and it turns out their metadata are not sensible. Not sure if that would take substantial time to write up.

Good idea, I was kind of waffling on this but hearing someone else ask for it the impetus I need to write something up.

**Comment by d-v-b** [comment]
closed as completed via #19
