### ISSUE TITLE
coordinateTransformation translation is optional

### ISSUE THREAD

**Issue by will-moore** [JaneliaSciComp/pydantic-ome-ngff#6]
The v0.4 spec contains the following statement about `coordinateTransformations` list:

```
It MAY contain exactly one translation that specifies the offset from the origin in physical units. If translation is given it MUST be listed after scale to ensure that it is given in physical coordinates. 
```

However, the following line asserts that there MUST be a `translation` coordinateTransformation that follows the `scale`.

https://github.com/JaneliaSciComp/pydantic-ome-ngff/blob/176e4521acb5b0e4e9d19f3e15e72fedf87789e4/src/pydantic_ome_ngff/v04/multiscales.py#L57

This causes a bunch of errors when I'm experimenting with using `pydantic-ome-ngff` within `ome-zarr-py`: https://github.com/ome/ome-zarr-py/pull/281#issuecomment-1542126253

**Comment by d-v-b** [comment]
thanks @will-moore, I will get this fixed up today.
